# logstash/config/logstash.yml

http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
pipeline.workers: 1
pipeline.batch.size: 125
pipeline.batch.delay: 50
path.data: /usr/share/logstash/data
config.reload.automatic: true
config.reload.interval: 3s
queue.type: memory